// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Offer_API.Repository;

#nullable disable

namespace Offer_API.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    [Migration("20250715153627_InitializeRelease")]
    partial class InitializeRelease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("Offer_API.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Model = "Camry",
                            RegistrationDate = new DateTime(2025, 7, 10, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4184),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            Model = "Civic",
                            RegistrationDate = new DateTime(2025, 7, 11, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4186),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Ford",
                            Model = "Focus",
                            RegistrationDate = new DateTime(2025, 7, 12, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4188),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BMW",
                            Model = "X5",
                            RegistrationDate = new DateTime(2025, 7, 13, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4190),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Audi",
                            Model = "A4",
                            RegistrationDate = new DateTime(2025, 7, 14, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4191),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Mercedes",
                            Model = "C-Class",
                            RegistrationDate = new DateTime(2025, 7, 15, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4193),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Daewoo",
                            Model = "Matiz",
                            RegistrationDate = new DateTime(2025, 7, 9, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4195),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Hyundai",
                            Model = "Tucson",
                            RegistrationDate = new DateTime(2025, 7, 10, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4196),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Kia",
                            Model = "Sportage",
                            RegistrationDate = new DateTime(2025, 7, 11, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4198),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Nissan",
                            Model = "Juke",
                            RegistrationDate = new DateTime(2025, 7, 12, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4200),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Chevrolet",
                            Model = "Malibu",
                            RegistrationDate = new DateTime(2025, 7, 13, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4201),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Tesla",
                            Model = "Model 3",
                            RegistrationDate = new DateTime(2025, 7, 14, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4203),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Subaru",
                            Model = "Outback",
                            RegistrationDate = new DateTime(2025, 7, 15, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4204),
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Mazda",
                            Model = "Miata",
                            RegistrationDate = new DateTime(2025, 7, 14, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4206),
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Lada",
                            Model = "Samara",
                            RegistrationDate = new DateTime(2025, 7, 13, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4208),
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("Offer_API.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 15, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4057),
                            Name = "Делимобиль"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 20, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4073),
                            Name = "Тачковоз"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 25, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4074),
                            Name = "ООО Тмыв"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 6, 30, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4076),
                            Name = "Газпром"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 7, 5, 18, 36, 26, 529, DateTimeKind.Local).AddTicks(4077),
                            Name = "Моторчик"
                        });
                });

            modelBuilder.Entity("Offer_API.Models.Offer", b =>
                {
                    b.HasOne("Offer_API.Models.Supplier", "Supplier")
                        .WithMany("Offers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Offer_API.Models.Supplier", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
