// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Offer_API.Repository;

#nullable disable

namespace Offer_API.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    [Migration("20250715143921_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("Offer_API.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Model = "Camry",
                            RegistrationDate = new DateTime(2025, 7, 10, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1213),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            Model = "Civic",
                            RegistrationDate = new DateTime(2025, 7, 11, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1217),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Ford",
                            Model = "Focus",
                            RegistrationDate = new DateTime(2025, 7, 12, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1220),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BMW",
                            Model = "X5",
                            RegistrationDate = new DateTime(2025, 7, 13, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1223),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Audi",
                            Model = "A4",
                            RegistrationDate = new DateTime(2025, 7, 14, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1225),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Mercedes",
                            Model = "C-Class",
                            RegistrationDate = new DateTime(2025, 7, 15, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1228),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Daewoo",
                            Model = "Matiz",
                            RegistrationDate = new DateTime(2025, 7, 9, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1230),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Hyundai",
                            Model = "Tucson",
                            RegistrationDate = new DateTime(2025, 7, 10, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1232),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Kia",
                            Model = "Sportage",
                            RegistrationDate = new DateTime(2025, 7, 11, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1235),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Nissan",
                            Model = "Juke",
                            RegistrationDate = new DateTime(2025, 7, 12, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1237),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Chevrolet",
                            Model = "Malibu",
                            RegistrationDate = new DateTime(2025, 7, 13, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1239),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Tesla",
                            Model = "Model 3",
                            RegistrationDate = new DateTime(2025, 7, 14, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1242),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Subaru",
                            Model = "Outback",
                            RegistrationDate = new DateTime(2025, 7, 15, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1245),
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Mazda",
                            Model = "Miata",
                            RegistrationDate = new DateTime(2025, 7, 14, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1247),
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Lada",
                            Model = "Samara",
                            RegistrationDate = new DateTime(2025, 7, 13, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1249),
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("Offer_API.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 15, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1027),
                            Name = "Делимобиль"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 20, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1047),
                            Name = "Тачковоз"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 25, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1050),
                            Name = "ООО Тмыв"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 6, 30, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1052),
                            Name = "Газпром"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 7, 5, 17, 39, 21, 552, DateTimeKind.Local).AddTicks(1054),
                            Name = "Моторчик"
                        });
                });

            modelBuilder.Entity("Offer_API.Models.Offer", b =>
                {
                    b.HasOne("Offer_API.Models.Supplier", "Supplier")
                        .WithMany("Offers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Offer_API.Models.Supplier", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
