// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Offer_API.Repository;

#nullable disable

namespace Offer_API.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    partial class OfferDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Offer_API.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Model = "Camry",
                            RegistrationDate = new DateTime(2025, 7, 11, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5616),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            Model = "Civic",
                            RegistrationDate = new DateTime(2025, 7, 12, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5617),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Ford",
                            Model = "Focus",
                            RegistrationDate = new DateTime(2025, 7, 13, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5619),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BMW",
                            Model = "X5",
                            RegistrationDate = new DateTime(2025, 7, 14, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5620),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Audi",
                            Model = "A4",
                            RegistrationDate = new DateTime(2025, 7, 15, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5621),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Mercedes",
                            Model = "C-Class",
                            RegistrationDate = new DateTime(2025, 7, 16, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5623),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Daewoo",
                            Model = "Matiz",
                            RegistrationDate = new DateTime(2025, 7, 10, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5624),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Hyundai",
                            Model = "Tucson",
                            RegistrationDate = new DateTime(2025, 7, 11, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5625),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Kia",
                            Model = "Sportage",
                            RegistrationDate = new DateTime(2025, 7, 12, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5626),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Nissan",
                            Model = "Juke",
                            RegistrationDate = new DateTime(2025, 7, 13, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5628),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Chevrolet",
                            Model = "Malibu",
                            RegistrationDate = new DateTime(2025, 7, 14, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5629),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Tesla",
                            Model = "Model 3",
                            RegistrationDate = new DateTime(2025, 7, 15, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5630),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Subaru",
                            Model = "Outback",
                            RegistrationDate = new DateTime(2025, 7, 16, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5631),
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Mazda",
                            Model = "Miata",
                            RegistrationDate = new DateTime(2025, 7, 15, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5632),
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Lada",
                            Model = "Samara",
                            RegistrationDate = new DateTime(2025, 7, 14, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5634),
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("Offer_API.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 6, 16, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5503),
                            Name = "Делимобиль"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 6, 21, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5517),
                            Name = "Тачковоз"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 6, 26, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5519),
                            Name = "ООО Тмыв"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 7, 1, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5520),
                            Name = "Газпром"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 7, 6, 22, 30, 53, 380, DateTimeKind.Local).AddTicks(5521),
                            Name = "Моторчик"
                        });
                });

            modelBuilder.Entity("Offer_API.Models.Offer", b =>
                {
                    b.HasOne("Offer_API.Models.Supplier", "Supplier")
                        .WithMany("Offers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Offer_API.Models.Supplier", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
